@echo off
echo ****************Installing Chocolatey********************

@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
mkdir c:\ProgramData\Chocolatey\license
@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "Invoke-WebRequest 'https://cirrus.thejohnweb.com/s/Pwm5piyyRYPgsjo/download/chocolatey.license.xml.txt' -OutFile 'c:\ProgramData\chocolatey\license\chocolatey.license.xml' -PassThru | Select-Object -ExpandProperty Content"
@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "Install-WindowsFeature NET-Framework-Core NET-Framework-45-Core GPMC Windows-Defender RSAT RSAT-Feature-Tools RSAT-SMTP RSAT-Feature-Tools-Bitlocker RSAT-Bits-Server RSAT-NLB RSAT-SNMP RSAT-Role-Tools RSAT-AD-Tools RSAT-AD-PowerShell RSAT-ADDS RSAT-AD-AdminCenter RSAT-ADDS-Tools RSAT-ADLDS RSAT-Hyper-V-Tools Hyper-V-Tools Hyper-V-PowerShell RSAT-RDS-Tools UpdateServices-RSAT UpdateServices-API UpdateServices-UI RSAT-ADCS RSAT-ADCS-Mgmt RSAT-Online-Responder RSAT-ADRMS RSAT-DHCP RSAT-DNS-Server RSAT-Fax RSAT-File-Services RSAT-NetworkController RSAT-NPAS RSAT-Print-Services RSAT-RemoteAccess RSAT-RemoteAccess-Mgmt RSAT-RemoteAccess-Powershell RSAT-VA-Tools WDS-AdminPackInstall-WindowsFeature NET-Framework-Core,NET-Framework-45-Core,GPMC,Windows-Defender,RSAT,RSAT-Feature-Tools,RSAT-SMTP,RSAT-Feature-Tools-Bitlocker,RSAT-Bits-Server,RSAT-NLB,RSAT-SNMP,RSAT-Role-Tools,RSAT-AD-Tools,RSAT-AD-PowerShell,RSAT-ADDS,RSAT-AD-AdminCenter,RSAT-ADDS-Tools,RSAT-ADLDS,RSAT-Hyper-V-Tools,Hyper-V-Tools,Hyper-V-PowerShell,RSAT-RDS-Tools,UpdateServices-RSAT,UpdateServices-API,UpdateServices-UI,RSAT-ADCS,RSAT-ADCS-Mgmt,RSAT-Online-Responder,RSAT-ADRMS,RSAT-DHCP,RSAT-DNS-Server,RSAT-Fax,RSAT-File-Services,RSAT-NetworkController,RSAT-NPAS,RSAT-Print-Services,RSAT-RemoteAccess,RSAT-RemoteAccess-Mgmt,RSAT-RemoteAccess-Powershell,RSAT-VA-Tools,WDS-AdminPack"
choco feature enable -n allowGlobalConfirmation
choco install choco.extension
choco install Waterfox vscode rvtools putty vmwareworkstation git vmwarevsphereclient openssl termius --pre ssms office365business nextcloud-client mRemoteNG GoogleChrome gitkraken db-visualizer bitwarden awscli 7zip gow wget
choco install sysinternals --skip-virus-check

